#!/bin/bash

export PKG_CONFIG_PATH=/opt/opencv-3.3.1/lib/pkgconfig
export PATH=/opt/opencv-3.3.1/bin:/usr/local/cuda-10.0/bin:$PATH
export LD_LIBRARY_PATH=/opt/opencv-3.3.1/lib:/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

${SCRIPT_DIR}/darknet "$@"
